spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:mysql://localhost:3306/task_manager_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "ReplaceThisWithAVeryLongRandomBase64EncodedSecretKeyForJWTSigning123456"
  expiration-ms: 900000        # 15 minutes
  refresh-expiration-ms: 604800000   # 7 days

logging:
  level:
    com.digitalwallet: DEBUG